title: My New Homepage
email: tim293130@gmail.com
description: >-
  This is my awesome website about technology and coding.
url: "https://graysandwich.github.io"
github_username: graysandwich

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
